version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: retail-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=retail_management_db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: retail-backend
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=retail_management_db
      - CORS_ORIGINS=*
      - JWT_SECRET_KEY=retail-management-secret-key-change-in-production
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: retail-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

volumes:
  mongodb_data: